version: '2'
services:
  redis:
    image: redis
    ports:
     - "6379"
  db3:
    build: ./db/
    ports:
     - "5432"

  web10:
    build: .
    ports:
     - "5000:5000"
    depends_on:
     - redis
     - db3
    volumes:
     - ./:/app
  worker2:
    build: ./worker
    depends_on:
     - redis
     - db3
    volumes:
     - ./:/app
