import os

DATABASE_URL = os.getenv('DATABASE_URL', 'redis://localhost:6379')

# Global config for all examples
scrumdo_username = os.getenv('SCRUMDO_USERNAME', 'user')
scrumdo_password = os.getenv('SCRUMDO_PASSWORD', 'pass')

scrumdo_host = "https://app.scrumdo.com"
organization_slug = "org"




DEBUG = True
SECRET_KEY = 'UUC5324K4D2PNQR0123EEECGF3'
SQLALCHEMY_DATABASE_URI = DATABASE_URL
SQLALCHEMY_TRACK_MODIFICATIONS = True
SECURITY_POST_LOGIN_VIEW = '/'
SECURITY_PASSWORD_HASH = 'YIX0N2GDH7M1AA85V9TT'
SECURITY_PASSWORD_SALT = '8OS94MDLPG0732DXWYW0'
SECURITY_REMEMBER_SALT = '68QIXVBSDKX528ZLEH0A'
SECURITY_RESET_SALT = 'UH942QNAZ1HJ5TPTV4OA'
SECURITY_RESET_WITHIN = '5 days'
SECURITY_CONFIRM_WITHIN = '5 days'
RECAPTCHA_PARAMETERS = { 'render': 'explicit'}
RECAPTCHA_DATA_ATTRS = {'theme': 'dark'}
RECAPTCHA_PUBLIC_KEY = "6LfyEw4TAAAAAEf7aOIbBPbdf23IRdhfCFfJXeQJ"


